facebook/fbjs

scripts/babel/rewrite-requires.js
I think we'll want to make this more flexible at some point in the future (eg, for commonJS paths it probably shouldn't do anything)
=> Only rewrite rewrite requires for literals

package.json
Silences this warning when running `npm install`:
```
npm WARN package.json fbjs@0.1.0-alpha.1 No repository field.
```
=> Add "repository" to package.json

gulpfile.js, scripts/jest/preprocessor.js, src/polyfill/Promise.js
Instead of using `_moduleMap`, this adds a `Promise` module that simply exports `promise`.
Ideally, we would just use `_moduleMap` and avoid the (tiny) overhead of having a `Promise` module. However, this is insufficient for Flow which processes the files pre-transpilation. Without this, `flow check` would complain that it cannot find a module named `Promise`.
=> Replace Promise => promise module mapping with Promise module

gulpfile.js, package.json, scripts/jest/preprocessor.js, src/fetch/__mocks__/fetch.js, src/fetch/__mocks__/fetchWithRetries.js, src/fetch/__tests__/fetchMock-test.js, src/fetch/__tests__/fetchWithRetries-test.js, src/fetch/fetch.js, src/fetch/fetchWithRetries.js
Adds the `fetchWithRetries` module. This requires a `fetch` polyfill, so I've also added `whatwg-fetch` as a package dependency.
I also had to add the `es7.objectRestSpread` Babel transform because `fetchWithRetries` uses a destructured assignment with object rest properties.
=> Add `fetchWithRetries` and `fetch` polyfill

scripts/gulp/module-map.js
My module-map.json contained only an empty object, post-build, on my machine. Making the `@providesModule` regex less restrictive with respect to line breaks fixed it.
=> Match \r or \r\n linebreaks when scanning for @providesModule

gulpfile.js
Prevents these requires from being rewritten as `require('./es6-map')`, et cetera.
=> Map es6-map, promise, and whatwg-fetch to the corresponding npm modules

src/__forks__/warning.js, src/stubs/EventListener.js
- EventListener is just some reorganized logic.
- warning has the runtime argument check removed. We have a lint rule in
React for that (which I'll bring over here at some point). We have the
same rule internally.
=> Sync a couple changes from React

gulpfile.js, package.json, scripts/jest/preprocessor.js
This should make it such that we can properly run flow in projects consuming fbjs.
(Sorry for the package.json noise, npm3 sorts on writing)
=> Include flow comments in compiled output

gulpfile.js, package.json, scripts/babel/rewrite-modules.js
Exports manual mocks so that composite projects can run tests using them.
=> Build manual mocks into lib/__mocks__

src/fetch/fetchWithRetries.js
Changes the Flow annotations for `fetchWithRetries` to make it easier to compose.
=> Make `fetchWithRetries` configs optional

scripts/babel/rewrite-modules.js
Fixes #31
This still allows other crappy prefixes like `false`. We could probably do a `typeof === 'string'` check instead…
cc @yungsters
=> Respect the empty string as a module rewrite prefix

scripts/jest/preprocessor.js, src/fetch/__tests__/fetchWithRetries-test.js
Ugh... not sure what the deal is with Jest and `promise`, but going to just disable these tests for now.
Originally reported by @glenjamin via #36.
cc @cpojer
=> Disable broken tests in fetchWithRetries-test.js

src/.flowconfig
The `flow/include` directory only contains output for consumers of **facebook/fbjs**. These double up on all the definitions in `src/`.
Fixing this fixes all the issues when running `flow check src`.
=> Remove `../flow` from .flowconfig

.travis.yml, package.json
`flow-bin` downloads flow and sets that up so we don't have to worry about that, which is nice.
I think this will do what we want… fail for both typechecks and tests. We'll need to turn on travis though to actually see.
=> Enable TravisCI, typecheck

scripts/babel/inline-requires.js
For some reason, `npm link` didn't have an issue with this. I made sure that this works by monkey-patching the install of alpha11 inside of Relay.
=> Fix import to require `babel-core`

gulpfile.js, package.json, scripts/README.md, scripts/package.json
Not quite done but gets the plan across. The problem I'm trying to solve here is make it possible to ship more and more support scripts without bloating the production dependencies (eg, lint is coming). Everything I moved from `devDependencies` into fbjs-scripts actually should have been a regular dependency of fbjs (but wasn't so using some scripts was actually broken). The flow stuff sits somewhere in between so I just left it as something that gets shipped with fbjs.
This uses `file:scripts` to pull in `fbjs-scripts` as a package without having to hit npm. This will also let us make changes to fbjs tooling without having to ship it to npm to actually use it, then we can ship it when it's ready. Changes will need 'npm install ./scripts' to be run (since it's copied, but I think this …
=> Split scripts into standalone package

scripts/node/check-dev-engines.js, scripts/package.json
This brings in the script that we're using in React to make sure the dev environment is what we expect. It's slightly modified to require a file argument since we can't hardcode the path to the `package.json` that we want to use. Specifically it checks `devEngines` in package.json, which is something I made up (but correlates nicely with the `engines` field that npm sort of uses)
I confirmed this is working in React with
```json
"scripts": {
"preinstall": "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"
}
```
=> Port dev engines script from React

scripts/eslint/.eslintrc
This pulls in out internal eslint config into something we can start using in downstream projects with minimal overrides (eg we're a bit stricter in React but probably don't want to be in Relay). We can continue down this path and bring in some custom rules next - we have a number of internal ones that were written and would be good to have out here to maintain consistency.
Note: this was branched from #48 so it has that totally unrelated dev engines script.
=> Eslint base config

package.json, scripts/jest/createCacheKeyFunction.js
We don't need it because it can't influence the output of a test file. It is also not being stringified consistently and results in more cache misses than necessary.
=> Ignore `config` option when creating a cache key.

src/fetch/__tests__/fetchWithRetries-test.js, src/fetch/fetchWithRetries.js
After the last retry fails, the Promise should be rejected with an `Error` instead of the fetch `Response` object.
This will parse the body and append it to the returned `Error` object.
Fixes https://github.com/facebook/relay/issues/347
=> Ensure fetchWithRetries is rejected with an Error

src/core/__tests__/dom/getActiveElement-test.js, src/core/dom/getActiveElement.js
when `document` does not exist
While using great library `react-unit` to test the React components I discovered that this function is the only part that needs `document` global otherwise it crashes (variable not defined). This is an attempt to make it work even without document.
I've added simple test to verify basic functionality, but haven't figure out how to test my scenario when `document` is not present.
Thanks a lot and looking forward for the feedback...
=> Fix getActiveElement so that it does not throw error

src/core/__tests__/joinClasses-test.js, src/core/__tests__/memoizeStringOnly-test.js, src/core/joinClasses.js, src/core/memoizeStringOnly.js
Wanted to move a couple things our of React. I just threw them in core like everybody else but they can be moved later (the important part is getting them out of React). There are certainly more but these came up in a couple discussions recently.
Note: I still need to do this internally and we'll have to do a diff to React to remove and update the fbjs dep. It would be safe to land this and not update React immediately (they'll be under completely different paths after compilation).
`memoizeStringOnly` is used by UserAgent (#57 commented out in the code there)
`joinClasses` is used by a bunch of components and surely non-React code and I'd rather not map them into React if we open source any of them. Not to mention that there is nothing React specific about it.
cc @yungsters @spicyj
=> Bring in some modules from React

package.json
* https://github.com/facebook/react/commit/6fc53e043876f5b53b144847faaeb7ea4398f9c3#diff-c3a9ce50ac626f89fa72fdcb514bf9e9R110 works fine for building the dist `react.js`, but users who `require('react')` aren't getting fbjs envified. So someone using browserify is getting the `process` shim included, which is like 2kb and has an empty env – so `process.env.NODE_ENV !== 'production'` is always true for fbjs stuff. I took the liberty of using `loose-envify` because it's fast (I'm using it in [invariant](https://github.com/zertosh/invariant) already) – but feel free to remove it in favor of the actual envify.
<del>* Even though `flow/include` is in `.gitignore`, because `"files"` is used (instead of `.npmignore`), the published package includes it.</del>
=> browserify friendliness

scripts/eslint/.eslintrc
Enabling `comma-dangle` to warn if there is a missing trailing comma on arrays or objects that span multiple lines, and warn if there is a trailing comma present on single line arrays or objects.
Trailing commas simplify adding and removing items to objects and arrays, since only the lines you are modifying must be touched.
> This commit message was shamelessly jacked from [the ESLint website](http://eslint.org/docs/rules/comma-dangle.html).
=> Enable `comma-dangle` as an eslint warning

src/__forks__/invariant.js, src/core/__tests__/PromiseMap-test.js
Gets rid of the "Invariant Violation: " message prefix in favor of setting the `error.name` to "Invariant Violation".
=> "Invariant Violation" as Error Name

package.json, scripts/jest/createCacheKeyFunction.js, scripts/jest/preprocessor.js
updated createCacheKeyFunction to use the correct config object for creating the hash; this was a breaking change in jest.
=> Update to jest 0.6.0

scripts/babel-6/auto-importer.js, scripts/babel/auto-importer.js, scripts/babel/default-options.js
Adds auto-importer transform (Babel 5 and 6 versions). We auto-import `Promise` module, and also `regeneratorRuntime`.
=> [babel] Add auto-importer transform

gulpfile.js, package.json, scripts/babel/default-options.js, scripts/gulp/module-map.js, scripts/gulp/shared/provides-module.js, scripts/gulp/strip-provides-module.js, src/__forks__/Promise.native.js, src/__forks__/fetch.js, src/stubs/ErrorUtils.js
This PR performs the necessary changes to `fbjs` to allow for better compatibility with React Native, post the https://github.com/facebook/react-native/commit/6a838a4201f99ae5e88b3684bb798d363815dd53 commit.
TLDR; this PR does the following:
1. Strips the `@providesModule` directives from the built, npm version of fbjs (courtesy of @zpao). This is no longer necessary after https://github.com/facebook/react-native/pull/5084 is merged.
2. Switch to `isomorphic-fetch`, in order to avoid causing weird `require` issues that happen when the `whatwg-fetch` module is required on React Native (courtesy of @zpao). Also fixes the issues discussed in https://github.com/facebook/fbjs/pull/61, which is where this commit is from.
3. Adds the React Native promise implementation as `Promise.native.js`. …
=> [RFC] RN 0.18 Compatibility changes

src/core/dom/__tests__/getActiveElement-test.js, src/core/dom/getActiveElement.js
Brings back #59, which was unintentionally reverted by 03ce16e.
=> FBJS: Fix `getActiveElement` w/o `document`

src/core/shallowEqual.js
Forgive me if I'm overlooking something obvious, but there doesn't seem to be a good reason to use bind here. It's still really slow. Using .call is a lot faster and seems to have no negative tradeoffs. Given that this method gets used in react's shallowCompare utility, which in turn finds its way into people's shouldComponentUpdate methods, it really seems like there are good reasons to be persnickety about .bind's performance.
I'm including a test on [jsperf](http://jsperf.com/shallowequal-call-vs-bind) (yeah, I know. Sorry). That naïvely demonstrates a 4x perf improvement (on Chrome 47) with this simple change.
=> make shallowEqual use call instead of bind

package.json, src/__forks__/Promise.native.js
This is to mimic and keep in sync the change from React Native on `Promise.js`.
Commit in question: https://github.com/facebook/react-native/commit/b0640946873945ee95d2cab8f549c915dbfffd70
Hopefully we won't have to do too many of these pending the fbjs changes in the RN packager.
=> Add support for promise rejection tracking in native Promise polyfill

scripts/babel/default-options.js
Not having this module listed in the default options breaks `Promise.native.js` on build, as it `requires('./promise/setimmediate/rejection-tracking')` rather than the proper module sans the `./`.
/cc @zpao @martinbigio
=> Adding rejection-tracking promise module to module map

CHANGELOG.md, src/stubs/URI.js
Was working on a project using URI and hit the expectation that stringifying an instance would give a string uri back.
=> Update URI stub to have most basic expected functionality: stringification

CHANGELOG.md, scripts/babel/default-options.js, src/__forks__/Promise.native.js
After discussion with @davidaurelio, this PR moves the Promise rejection tracking code out of fbjs (really shouldn't have been in there in the first place), and instead just makes fbjs export a React Native compliant version of Promise, rather than adding functionality.
The corresponding change in RN will require the release of 0.7.2 of fbjs.
=> Move RN Promise rejection tracking code out of fbjs

package.json
`babel-eslint@4.1.5` was broken with the version of Babel that's used on this package. This updates babel-eslint to the latest 4.x point release, which fixes the `visitClass` error that you see in CI.
=> Update babel-eslint to fix eslint in CI.

.travis.yml, package.json, scripts/CHANGELOG.md, scripts/node/check-lib-requires.js
Quick and dirty but it works. It turns out I missed a dependency while working on #113 so this will now prevent the build from completing successfully. It's written so that any of our other projects should be able to use it too.
Fixes #68
=> [scripts] Check that all lib files can be required

scripts/CHANGELOG.md, scripts/babel-6/__tests__/rewrite-modules-test.js, scripts/babel-6/rewrite-modules.js, scripts/babel/rewrite-modules.js
Also slipped in a related-ish change, to preserve all arguments when
rewriting the first. This was required to support the `jest.setMock`
use.
=> [babel] Rewrite more jest methods

gulpfile.js, package.json, scripts/babel-6/default-options.js, scripts/third-party-module-map.json, src/functional/compactArray.js
Now that we are on Babel 6, it's easy to pull in only the transforms that we need, leaving the rest intact.
Fixes #118
Test Plan:
Took the diff of the current master's `lib` and this PR's. It's pretty noisy, but you can see that the local requires are relative and node_module requires remain absolute. https://gist.github.com/samwgoldman/028cf76abf1e072920c5
=> Relativize requires in .flow.js files

package.json
Closes #128.
After this, we can start going crazy with all the ES2015 features.
=> Bump devEngine requirement to node >=4

.gitignore, flow/lib/Promise.js
Flow 0.23 removed the un-speced methods from the Promise class, which is
the right thing to do. However our Promise impl does have those methods
and we use them so for now, the best thing to do is just ship the
Promise class definition that we are using. In the future we can stop
relying on that method.
Also fixed gitignore to pick up changes in `flow/lib` properly.
=> Add old Promise Flow definition

babel-preset/plugins/__tests__/rewrite-modules-test.js, babel-preset/plugins/rewrite-modules.js
Generate relative type imports in .js.flow files
This is the diff of the current master's lib and this PR's:
https://gist.github.com/tsing/afa63600f4aa41c729f3eb2017c862eb
=> Relativize type import in .flow.js files

README.md
The `rewrite-modules` script got moved, but the reference wasn't updated
=> README: fix broken link to rewrite-modules

packages/fbjs-css-vars/CHANGELOG.md, packages/fbjs-css-vars/LICENSE, packages/fbjs-css-vars/PATENTS, packages/fbjs-css-vars/README.md, packages/fbjs-css-vars/index.js, packages/fbjs-css-vars/package.json
This is motivated by the revival of fixed-data-table which uses our `cssVar` module and has variables in CSS. Draft also has some of these variables in its CSS. We do a simple replace in Draft's build process, which we can also do in FDT but to ensure our list stays up to date we want these in a shared place. I didn't just make a shared CSS transform since we also need these values to appear in JS. In the future we can write a Babel transform that replaces `cssVar` calls but the lowest friction thing is to just make this module a dependency of `fbjs` and read from it there.
=> [fbjs-css-vars] Initial release

packages/fbjs/src/__forks__/warning.js
Not a big deal but this can add up if a lot of elements are being created (such as the case with FixedDataTable).
Before:
After:
=> Extract try/catch into a separate function to prevent deopt

packages/eslint-config-fbjs/CHANGELOG.md, packages/eslint-config-fbjs/package.json, packages/eslint-config-fbjs/strict.js
This is the default config, with all rules that were warnings upgraded to errors.
We've wanted a stricter version of the config so that warnings don't slip past travis. So this is that.
=> [eslint-config-fbjs] Create a "strict" config

packages/fbjs/flow/lib/dev.js
This is primarily for direct consumers who want to use `__DEV__` in
their code and run flow on that code before the `__DEV__` transform is
run.
cf #185
=> [fbjs] Restore flow/lib/dev.js

packages/babel-preset-fbjs/CHANGELOG.md, packages/babel-preset-fbjs/configure.js, packages/babel-preset-fbjs/plugins/__tests__/dev-declaration-test.js, packages/babel-preset-fbjs/plugins/dev-declaration.js
This allows us to continue using `__DEV__` in our code without having
a separate include that must be used anytime that `fbjs` (or other
projects using the same pattern) is used.
This is the diff after building fbjs on master: https://gist.github.com/zpao/8694c44a2aa1d52382059099d1006833
cf #185.
cc @gabelevi. This is what I was talking about. I *think* it makes sense but would love the Flow insider opinion now that it's real. I don't love that this seems to be the only way to do this right now.
=> [babel-preset-fbjs] Add __DEV__ flow declaration when used

packages/fbjs/src/__forks__/Style.js, packages/fbjs/src/__forks__/getUnboundedScrollPosition.js, packages/fbjs/src/core/dom/__tests__/getActiveElement-test.js, packages/fbjs/src/core/dom/getActiveElement.js, packages/fbjs/src/core/dom/getElementRect.js, packages/fbjs/src/core/dom/getScrollPosition.js, packages/fbjs/src/core/dom/isNode.js
Fixes #156. In the discussion in that issue, @spicyj wrote:
> If this is causing a problem in some Facebook project using fbjs, feel free to send a pull request.
I’ve seen a couple issues that I’m hoping can qualify, including:
facebook/react#427
facebook/draft-js#527
I can also say that I am working with a team on an editor app that would benefit greatly from having React, Draft.js, and fbjs all work seamlessly across iframes. When building a sophisticated editor of some kind, the use case of rendering from a single parent browsing context into a separate nested browsing context, treating it as a sandboxed rendering target that can publish UI events, is a really compelling one.
About the PR: We used eslint’s `no-undef` rule with a config that didn’t include the browser env to get a list …
=> Make DOM utilities work in nested browsing contexts

packages/babel-preset-fbjs/plugins/__tests__/dev-declaration-test.js
Babel now prints boolean as boolean, this updates the test.
=> [babel-preset-fbjs] fix dev-declaration plugin

packages/fbjs/src/__forks__/invariant.js
This allows us to only check DEV (or process.env.NODE_ENV) only once, at module initialization time, instead of during each call to invariant. But otherwise should maintain the current behavior.
cc @spicyj @cpojer @jeanlauliac @davidaurelio
=> [fbjs] Move DEV check out of invariant itself

packages/fbjs/package.json, packages/fbjs/src/.flowconfig, packages/fbjs/src/functional/partitionObjectByKey.js
`flow-bin@0.38.0` will throw the following error:
```bash
src/functional/partitionObjectByKey.js:25
25:   return partitionObject(source, (_, key) => whitelist.has(key));
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ tuple type. This type is incompatible with the expected return type of
24: ): Array<Object> {
^^^^^^^^^^^^^ array type
```
This PR fixes the flow typings of `partitionObjectByKey` to match [`partitionObject`](https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/functional/partitionObject.js#L18).
We discovered this problem in https://github.com/nteract/nteract/pull/1349 while trying to upgrade `flow-bin`.
=> Fix flow typings of partitionObjectByKey

packages/fbjs/src/core/dom/getActiveElement.js
Referencing `document` here throws an error in Node.
Using `global.document` avoids this.
Fixes #225
=> Use global.document in getActiveElement

packages/babel-preset-fbjs/plugins/__tests__/inline-requires-test.js, packages/babel-preset-fbjs/plugins/inline-requires.js
While syncing the latest React release to fbsource I discovered an improperly handled inlining case.
Essentially this:
```js
function foo() {
bar();
}
var bar = require('baz');
foo();
```
Became this (and errored because `bar` was undefined):
```js
function foo() {
bar();
}
foo();
```
After this bugfix it becomes:
```js
function foo() {
require("baz")();
}
foo();
```
=> inline-requires handles Identifiers declared before CallExpressions

packages/babel-preset-fbjs/plugins/__tests__/inline-requires-test.js, packages/babel-preset-fbjs/plugins/inline-requires.js
My [recent changes to the inline-requires transform](https://github.com/facebook/fbjs/pull/236) caused unintended problems when ran alongside other transforms (eg 'babel-plugin-transform-es2015-modules-commonjs').
```js
// This...
import Imported from 'XHRHttpError';
// Would be transformed into this...
var _XHRHttpError2 = babelHelpers.interopRequireDefault(_XHRHttpError);
```
The fix for this is to avoid re-processing the entire AST as we may interfere with modifications made by other plug-ins. Instead the 'inline-requires' transform tracks `Identifier`s and updates them (only) if we later remove a `require` they were depending on.
=> Make inline-require transform compatible with other transforms

packages/fbjs/package.json, packages/fbjs/src/.flowconfig, packages/fbjs/src/key-mirror/keyMirror.js, packages/fbjs/src/struct/PrefixIntervalTree.js
Adds flow annotations to `keyMap`, so that the return type is an object with all keys of the input object, and `string` values.
=> Type `keyMap`

packages/fbjs-scripts/gulp/check-dependencies.js
Alternative to #242, not relying on return codes at all but just blindly parsing the JSON.
Does this make sense @watilde? I haven't tested the output of `npm outdated` here to see if this will be versatile enough but I want to assume it's ok and would work across versions without issue. Or is the output still going to be JSON formatted errors? (given my experience with npm that seems doubtful).
Thanks for the idea to ignore status codes entirely @wwalser 👍
=> [fbjs-scripts] Handle npm outdated exit codes

packages/babel-preset-fbjs/plugins/inline-requires.js
This also avoids unintentionally invoking `scope.hasBinding(...)` on Flow-based bindings and getting that obnoxious warning message.
=> [babel-preset-fbjs] Remove unused variables

packages/babel-preset-fbjs/plugins/__tests__/inline-requires-test.js, packages/babel-preset-fbjs/plugins/inline-requires.js
Patterns like `import {name} from 'module'` where not working properly.
This adds support for that pattern.
In addition, state is local to the traversal, to avoid leaking paths after using the plugin.
=> [inline-requires] Make named imports work

packages/fbjs-scripts/jest/createCacheKeyFunction.js
Jest uses an extra option to differentiate intstrumented cache files from non-instrumented (https://github.com/facebook/jest/blob/master/packages/jest-runtime/src/script_transformer.js#L70-L72)
and it seems like fbsource is failing to collect coverage without this option
=> add 'instrument' flag to createCacheKey fn

packages/fbjs/CHANGELOG.md, packages/fbjs/src/core/Deferred.js
Ignoring the eslint stuff, which I guess I forgot to push to master the other day (will fix in a bit)…
This should fix some of the issues that Relay is seeing, but it was pointed out that `then` should also be causing issues. Looking at https://github.com/facebook/relay/commit/68241f7c9126b6c44646ffb078df63c2e3810d43, it seems like those were probably just blanketed over with fixmes.
=> Sync over argument arity fixes for stricter Flow updates

packages/fbjs/src/core/dom/getDocumentScrollElement.js
This fixes draft-js#14 for Chrome with "Experimental Web Platform" enabled.
https://github.com/facebook/draft-js/issues/14
=> Try document.scrollingElement first in getDocumentScrollElement

packages/eslint-config-fbjs-opensource/README.md, packages/eslint-config-fbjs-opensource/index.js, packages/eslint-config-fbjs-opensource/package.json
This makes the -opensource version of the config use the same versions
of dependencies as the "standard" flavor.
~~It also, like the standard flavor, makes all eslint plugins
peerDependencies, and instructs the user to install them all in the
README.~~
=> eslint plugins: Synchronize dependency versions between -opensource and standard eslint configs

packages/fbjs-scripts/gulp/check-dependencies.js, packages/fbjs-scripts/gulp/module-map.js, packages/fbjs-scripts/gulp/strip-provides-module.js, packages/fbjs-scripts/package.json
=> Drop dependency on deprecated `gulp-util`

packages/eslint-config-fbjs/package.json
There are no breaking changes, it just uses babel@7 under the hood.
https://github.com/babel/babel-eslint/releases/tag/v8.0.0
=> Allow babel-eslint 8 in eslint-config-fbjs

packages/fbjs/package.json
Bump `ua-parser-js` to fix Regular Expression Denial of Service (ReDoS) detected by Snyk.io.
Snyk vulnerability info page:
https://snyk.io/vuln/npm:ua-parser-js:20180227
Original issue:
https://github.com/faisalman/ua-parser-js/issues/315
Refs #286, #289 - same change, but without `package.json` reformat.
=> bump ua-parser-js to fix RegExp DoS vulnerability

packages/babel-preset-fbjs/plugins/__tests__/inline-requires-test.js, packages/babel-preset-fbjs/plugins/inline-requires.js, packages/fbjs/src/__forks__/warning.js
Enables the inlining of expressions like `var x = require('foo').x`, which can come from a) an `import {x} from 'foo'`, b) `const {x} = require('foo')` or c) `const foo = require('foo'); const x = foo.x`. This will enable further optimizations when detecting dead `require`s.
I simplified the plugin by making use of other Babel utilities, so that we don't have to manually track variables and scopes, and we equally treat all inlinable expressions. Also fixed a bug where `var foo = require('foo'), bar = require('bar')` was not properly getting inlined.
Added tests to ensure that new cases are covered, made sure all existing ones still pass.
=> Destructuring requires

packages/babel-preset-fbjs/plugins/__tests__/inline-requires-test.js, packages/babel-preset-fbjs/plugins/inline-requires.js
Make sure the inliner executes on exit, so that all the changes that have happened with intermediate syntax (e.g. JSX) and values (e.g. other plugins) are fully set.
Also, when a `require` gets redefined, avoid inlining it. This can legitimately happen when using generic helpers like `emptyObject` or `emptyFunction`.
=> Inline requires on exit

packages/babel-preset-fbjs/plugins/__tests__/inline-requires-test.js, packages/babel-preset-fbjs/plugins/inline-requires.js
Due to the fact that the same `require` call is getting inlined multiple times, the Chrome Developer Tool is showing multiple breakpoints at the requires. While this is _technically_ correct, it creates confusion, so we'll remove all location data from the node that will be moved.
Tests were added to ensure the behavior is correct.
=> Remove location when cloning "require" calls

packages/babel-preset-fbjs/plugins/__tests__/inline-requires-test.js, packages/babel-preset-fbjs/plugins/inline-requires.js
_Note: this PR is based in #301, which needs to be reviewed before reviewing this one._
Adds the ability of customizing the name of the calls that can be inlined. By default, this list is only composed by `require`. A test has been added to demonstrate the behavior.
=> Add the ability of inlining any call

packages/eslint-config-fbjs/package.json
No breaking changes from the perspective of this package
=> fix: allow babel-eslint 9 and eslint 5

packages/fbjs-scripts/package.json, packages/fbjs-scripts/yarn.lock, packages/fbjs/yarn.lock
#303 accidentally changed the dependency `fbjs-scripts` had on `babel-preset-fbjs` to be a relative file path. This breaks when installing `fbjs-scripts` from npm.
This commit fixes that
=> Fix fbjs-scripts dependency on babel-preset-fbjs

packages/babel-preset-fbjs/index.js
When running babel-preset-env ^3.0.0, I'm running into the following error:
```
Plugin/Preset files are not allowed to export objects, only functions. In /Users/jstejada/relay/node_modules/babel-preset-fbjs/index.js
```
This PR makes it so `babel-preset-env` exports the configure function by default
=> In Babel 7, a preset should always export a function by default

packages/babel-preset-fbjs/configure.js, packages/babel-preset-fbjs/package.json, packages/babel-preset-fbjs/yarn.lock, packages/fbjs-scripts/yarn.lock, packages/fbjs/yarn.lock
`@babel/plugin-check-constants` has been deprecated in Babel 7 in favor of [`@babel/plugin-transform-block-scoping`](https://babeljs.io/docs/en/babel-plugin-transform-block-scoping/), so we don't need to include it anymore.
This will get rid of any dependency on the old betas of Babel 7 ([more info](https://github.com/facebook/metro/issues/157)).
=> Remove unneeded @babel/plugin-check-constants plugin

.prettierrc.js, packages/babel-preset-fbjs/package.json, packages/babel-preset-fbjs/plugins/__tests__/__snapshots__/inline-requires-test.js.snap, packages/babel-preset-fbjs/plugins/__tests__/inline-requires-test.js, packages/babel-preset-fbjs/yarn.lock
Refactors the Jest test for `inline-requires` to use `babel-plugin-tester`.
=> Refactor inline-requires tests w/ babel-plugin-tester

packages/babel-preset-fbjs/package.json, packages/babel-preset-fbjs/plugins/inline-requires.js
Node 6 does not like trailing commas in function arguments
=> Fix Node 6 support

package.json, packages/eslint-config-fbjs/CHANGELOG.md, packages/eslint-config-fbjs/README.md, packages/eslint-config-fbjs/index.js, packages/eslint-config-fbjs/package.json, yarn.lock
The Relay eslint plugin is intended for product code, I don't think
it makes sense to pull in (likely outdated) GraphQL dependencies into
the framework projects using the fbjs eslint config.
=> [eslint-config-fbjs] remove relay dependency

packages/babel-preset-fbjs/plugins/__tests__/__snapshots__/inline-requires-test.js.snap, packages/babel-preset-fbjs/plugins/__tests__/inline-requires-test.js, packages/babel-preset-fbjs/plugins/inline-requires.js
In tests we sometimes use `require(require.resolve('module'))`, which is the same as `require('module')`, so we add an additional case to be sure both are inlined. Also added tests to verify the behavior.
=> Include "require.resolve" of a "require" as an inlineable call

.travis.yml
#332 is failing because Travis has an old version of Yarn (v1.3.2) installed. Output format has changed at some point (but semver?) so let's just make sure we're always running the latest.
=> Install latest yarn on TravisCI

packages/fbjs-scripts/CHANGELOG.md, packages/fbjs-scripts/jest/createCacheKeyFunction.js
This modifies the `createCacheKeyFunction` module to allow:
1. Passing custom values to take into account for the global cache breaker (no only files).
2. Ignoring the `rootDir` option of the Jest project so it enables remote caching.
I also added some missing entries in the changelog.
This has been tested in fbsource.
=> Remove rootDir from jest transformer cache key

packages/fbjs-scripts/gulp/check-dependencies.js
Prevents unsafe access to missing package data field (e.g. `resolutionDependencies`). Fixes #341
=> Prevents error when accessing missing package data field

package.json, packages/babel-preset-fbjs/package.json, packages/babel-preset-fbjs/plugins/__tests__/inline-requires-test.js, packages/babel-preset-fbjs/plugins/inline-requires.js, packages/babel-preset-fbjs/yarn.lock, packages/eslint-config-fbjs-opensource/package.json, packages/eslint-config-fbjs/package.json, packages/fbjs-scripts/package.json, packages/fbjs/package.json, packages/fbjs/src/.flowconfig, packages/fbjs/yarn.lock, yarn.lock
Align babel and eslint package versions to metro and react-native, to eliminate peer dependency warnings and an npm de-duplication problem.
Main repo didn't lint or prettier cleanly for me. I ran the prettier yarn target, but left the lint warnings alone.
The packages/* versions need to be bumped as well, but wasn't sure what the policy was. Tell me and I'll change them.
Some additional notes:
1. I tried bumping babel-plugin-tester to 5.6.x to eliminate another npm warning, but got some unhelpful test failure messages that I didn't have time to debug:
```
FAIL  plugins/__tests__/inline-requires-test.js
● inline-requires › ignores requires that are re-assigned
AssertionError [ERR_ASSERTION]: Expected output to not change, but it did
at tester …
```
=> Align versions to other facebook repos 

packages/fbjs/package.json, packages/fbjs/src/.flowconfig, packages/fbjs/src/core/emptyFunction.js, packages/fbjs/yarn.lock
Flow v0.99.0 is strict about function statics, which were previously typed as `any`. This added strictness causes issues for callers of the `emptyFunction` API involving static properties, like `emptyFunction.thatReturnsNull`.
This change updates the `emptyFunction` module to use a callable object type that also declares the types of the static properties. This might cause new Flow errors for library consumers.
=> Update Flow and fix emptyFunction type

packages/eslint-config-fbjs-opensource/package.json, packages/eslint-config-fbjs/package.json
Avoids a peer dep warning for Jest.
@cpojer something you can get landed and released?
=> fix: allow eslint v6 as peer dependency

packages/signedsource/__tests__/signedsource-test.js, packages/signedsource/index.js
The isSigned is inverted as #314 noted. Fixing that and updating tests. This allow now makes the re-signing of files with signFile to not fail. Adding a test for that too.
=> #314 - Fix isSigned being inverted. Add test for re-signing an existing file.

packages/babel-preset-fbjs/plugins/__tests__/__snapshots__/inline-requires-test.js.snap, packages/babel-preset-fbjs/plugins/__tests__/inline-requires-test.js, packages/babel-preset-fbjs/plugins/inline-requires.js
Currently, the `inline-requires` plugin breaks semantics when a property of a module is assigned a value. For example:
```
var X = require('X');
var origA = X.a;
X.a = function() {
origA();
};
```
Currently, this will become:
```
require('X').a = function() {
require('X').a();
};
```
Semantics are broken and this new code will loop infinitely. Instead, the intermediate `origA` alias must be preserved. This is the new output:
```
var origA = require('X').a;
require('X').a = function() {
origA();
};
```
**Test Plan:**
Ran `yarn test` and verified Jest snapshots.
=> inline-requires: Ignore modules with member assignmments

packages/fbjs/src/__forks__/invariant.js
Related issue: https://github.com/facebook/fbjs/issues/347
A change was made in https://github.com/facebook/fbjs/pull/240/files that incorrectly flipped the logic to only throw an error if `__DEV__ === false`. This would change it back to only throw the error if `__DEV__ === true` as was the behaviour previously.
=> Fix invariant function to throw error only if __DEV__ is true

.travis.yml
6 & 8 are ancient and don't reflect the real world. Use supported node
versions.
Built on #372
=> Use node 10 & 12 in CI

packages/fbjs-scripts/jest/environment.js, packages/fbjs-scripts/package.json, packages/fbjs-scripts/third-party-module-map.json, packages/fbjs-scripts/yarn.lock, packages/fbjs/package.json, packages/fbjs/src/__forks__/Map.js, packages/fbjs/src/__forks__/Set.js, packages/fbjs/yarn.lock
Every time I use yarn I get a warning about how core-js < 3 is not supported for `relay` and `flux` through `fbjs`. This migrates `core-js` to version 3 for `fbjs` and `fbjs-scripts`.
@zpao please, you're my only hope
=> [fbjs][fbjs-scripts] Upgrade core-js version

packages/fbjs-scripts/third-party-module-map.json, packages/fbjs/package.json, packages/fbjs/src/__forks__/__tests__/fetch-test.js, packages/fbjs/src/__forks__/fetch.js, packages/fbjs/yarn.lock
cross-fetch seems to be a drop-in replacement for isomorphic-fetch, but
more actively maintained. I also added a test to ensure we maintain the
behavior of using global fetch if available (eg React-Native)
closes #363
=> Replace isomorphic-fetch with cross-fetch

packages/fbjs-scripts/third-party-module-map.json
This will ensure users of fbjs-scripts keep the same old compat level
even if not updating fbjs.
Should have been left in there in #370.
=> Add entries for old core-js into module map

packages/fbjs-scripts/third-party-module-map.json
Oops, I missed these while grepping.
=> Remove `core-js` entries in third-party-module-map.

packages/eslint-config-fb-strict/index.js, packages/eslint-config-fb-strict/package.json
This currently lives in the Jest repo. I don't think there's a good reason for that, especially as that repo has moved away from Flow and `babel-eslint` towards a TS toolchain.
I plan to delete the source code from Jest's repo
https://github.com/facebook/jest/tree/92f74cd1fa057bc71890cd01018e6287fd24612b/packages/eslint-config-fb-strict
=> chore: move eslint-config-fb-strict into this repo

packages/babel-preset-fbjs/plugins/__tests__/__snapshots__/inline-requires-test.js.snap, packages/babel-preset-fbjs/plugins/__tests__/inline-requires-test.js, packages/babel-preset-fbjs/plugins/inline-requires.js
1. It's possible that the require is overridden in a module (or scope) and no longer points to the CommonJS require function. The plugin doesn't respect this. For this, we will now honor the require redeclaration if in global scope.
2. If the require function is re-declared in a sub-scope, e.g. a function. The plugin changes the semantics of the program by inlining the require call without renaming the scoped require declaration (it then accidentally calls the custom require implementation). This is fixed by renaming local scope "require" functions and calls to "_require"
=> Fix require shadowing in `inline-requires` plugin

packages/babel-preset-fbjs/plugins/__tests__/dev-declaration-test.js, packages/babel-preset-fbjs/plugins/__tests__/dev-expression-test.js, packages/babel-preset-fbjs/plugins/__tests__/inline-requires-test.js, packages/babel-preset-fbjs/plugins/__tests__/object-assign-test.js, packages/babel-preset-fbjs/plugins/__tests__/rewrite-modules-test.js, packages/babel-preset-fbjs/plugins/inline-requires.js, packages/babel-preset-fbjs/plugins/test-utils/validateOutputAst.js
Babel does not deal well with multiple references to the same node in a single AST. Specifically it can lead to `NodePath`s not being unique and therefore to incorrect scope analyses - see https://github.com/babel/babel/issues/6375 for pointers to manifestations of this in Babel.
These days, Babel's test suite ensures that Babel's first-party plugins do not emit such duplicates (https://github.com/babel/babel/pull/7149) but there is no such guarantee for third-party plugins.
This PR:
1. fixes the logic in `inline-requires` to avoid emitting repeated nodes.
2. adds tests to *all* the Babel plugins in this repo asserting that there are no repeated nodes in the resulting ASTs.
=> [babel-preset-fbjs] Avoid generating duplicate references to the same node

packages/fbjs-scripts/jest/createCacheKeyFunction.js
See https://github.com/facebook/jest/pull/10834
=> fix(jest): update cache function for new Jest 27 API

packages/fbjs/package.json, packages/fbjs/yarn.lock
Update cross-fetch to ^3.1.5 to resolve node-fetch's security vulnerability, [CVE-2022-0235](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-0235).
https://github.com/node-fetch/node-fetch/releases/tag/v2.6.7
Closes #471
=> Bump cross-fetch to resolve CVE-2022-0235

packages/babel-preset-fbjs/configure.js, packages/babel-preset-fbjs/package.json, packages/babel-preset-fbjs/yarn.lock
Both @babel/plugin-proposal-class-properties and @babel/plugin-proposal-object-rest-spread are now deprecated.
Fixes #518
See:
https://www.npmjs.com/package/@babel/plugin-proposal-class-properties https://www.npmjs.com/package/@babel/plugin-proposal-object-rest-spread
=> Replace deprecated dependencies
