facebook/fbjs

gulpfile.js
package.json
scripts/jest/preprocessor.js
src/core/Deferred.js
src/core/PromiseMap.js
src/core/__tests__/PromiseMap-test.js
src/core/resolveImmediate.js

Pulls in `Deferred` and `PromiseMap`. This also required adding `promise` as a package dependency and adding it to the `moduleMap` config.
**Test Plan:**
```
npm test
gulp
```

Add Deferred and PromiseMap dependencies

---

src/polyfill/Promise.js

Fix copyright header for Promise.js

---

package.json
src/polyfill/Map.js

Some future projects need a `Map` polyfill.

Add Map polyfill using es6-map

---

src/core/__tests__/shallowEqual-test.js
src/core/shallowEqual.js

Syncs `shallowEqual` into this repository. It is needed by future projects (not only `react`, which is where it currently resides).

Sync out `shallowEqual` (from React)

---

gulpfile.js
scripts/babel/default-options.js
scripts/jest/preprocessor.js

Reduces copypasta of config between `gulpfile.js` and the jest `preprocessor.js`.

Consolidate babel options

---

src/core/Deferred.js
src/core/ExecutionEnvironment.js
src/core/__tests__/PromiseMap-test.js
src/core/__tests__/areEqual-test.js
src/core/__tests__/removeFromArray-test.js
src/core/areEqual.js
src/core/createNodesFromMarkup.js
src/core/dom/containsNode.js
src/core/getMarkupWrap.js
src/core/isEmpty.js
src/fetch/__mocks__/fetchWithRetries.js
src/fetch/__tests__/fetchWithRetries-test.js
src/fetch/fetchWithRetries.js

Sync everything

---

scripts/jest/environment.js

Many future projects use ES2015 in both code and Jest tests. Let's set up the test environment for success.

Polyfill ES2015 in Jest

---

package.json

Remove `engines` from package.json

---

scripts/babel/default-options.js
scripts/babel/inline-requires.js
scripts/jest/createCacheKeyFunction.js
scripts/jest/preprocessor.js

Enable inline-require transform for tests.

---

src/crypto/__tests__/crc32-test.js
src/functional/__tests__/filterObject-test.js
src/functional/filterObject.js

Also, syncing a little change from internal.

Add functional/filterObject

---

scripts/eslint/.eslintrc

I won't claim this list is exhaustive (see https://github.com/facebook/flow/tree/master/lib for more) but it gets some out there.

[eslint] Add several globals used by Relay and others

---

CHANGELOG.md
package.json
scripts/babel/default-options.js
src/__forks__/UserAgentData.js
src/useragent/UserAgent.js
src/useragent/VersionRange.js
src/useragent/__tests__/UserAgent-test.js
src/useragent/__tests__/VersionRange-test.js

The goal here is to approximate our internal implementation, which is
all done server-side. This will not be perfect but we'll patch things up
as we need to.
We opted for ua-parser-js since it matches up pretty well with the handful of UAs we threw at it, has a fairly small footprint, is popular seems to be well supported.
cc @salier

Implement UserAgent fork using ua-parser-js

---

scripts/babel/inline-requires.js

Just some cleaning up to match up what I did internally. Doesn't affect functionality.

clean up inline-requires transform

---

scripts/package.json

Reverts facebook/fbjs#77
Reverting this because I don't like the version number and we should only bump that when we release anyway.

Revert c0e190114c52d9a1d0de4b510ab6c6efea40d8dd

---

scripts/babel/default-options.js

[babel] Move default plugins to before

---

CHANGELOG.md
gulpfile.js
package.json

I need to actually check that this is what we're expecting for the upcoming Flow release but I can fix that after we test.
cc @spicyj @gabelevi

Build .flow files next to .js files in lib

---

gulpfile.js
scripts/CHANGELOG.md
scripts/gulp/check-dependencies.js
scripts/package.json

This came out of a need where an issue with a project was fixed by upgrading dependencies but other team members were still seeing the issue since upgraded packages aren't caught in anyway.

[gulp] New script that checks that packages are up to date

---

CHANGELOG.md
package.json
scripts/third-party-module-map.json
src/core/Deferred.js
src/core/dom/containsNode.js
src/core/emptyFunction.js
src/core/memoizeStringOnly.js
src/datatransfer/DataTransfer.js
src/unicode/UnicodeUtilsExtra.js

Probably fine to ship this as 0.8.2. Biggest difference is that Flow will have a few more annotations to work from
cc @wincent

Sync from FB

---

packages/fbjs-scripts/third-party-module-map.json
packages/fbjs/CHANGELOG.md
packages/fbjs/package.json
packages/fbjs/src/__forks__/SiteData.js
packages/fbjs/src/__forks__/cssVar.js
packages/fbjs/src/__forks__/isEventSupported.js
packages/fbjs/src/__forks__/requestAnimationFramePolyfill.js
packages/fbjs/src/core/__tests__/debounceCore-test.js
packages/fbjs/src/core/cancelAnimationFramePolyfill.js
packages/fbjs/src/core/clamp.js
packages/fbjs/src/core/debounceCore.js
packages/fbjs/src/core/getVendorPrefixedName.js
packages/fbjs/src/dom/BrowserSupportCore.js
packages/fbjs/src/dom/DOMMouseMoveTracker.js
packages/fbjs/src/dom/ReactWheelHandler.js
packages/fbjs/src/dom/normalizeWheel.js
packages/fbjs/src/dom/translateDOMPositionXY.js
packages/fbjs/src/intl/Locale.js
packages/fbjs/src/struct/CircularBuffer.js
packages/fbjs/src/struct/Heap.js
packages/fbjs/src/struct/IntegerBufferSet.js
packages/fbjs/src/struct/PrefixIntervalTree.js
packages/fbjs/src/struct/__tests__/CircularBuffer-test.js
packages/fbjs/src/struct/__tests__/Heap-test.js
packages/fbjs/src/struct/__tests__/IntegerBufferSet-test.js
packages/fbjs/src/struct/__tests__/PrefixIntervalTree-test.js

I decided to update fixed-data-table. Some of what it had synced out are already here but other modules aren't.
There are still a couple more but wanted to checkpoint.

WIP: Sync most of what we need for fixed-data-table

---

packages/fbjs-scripts/CHANGELOG.md
packages/fbjs-scripts/gulp/check-dependencies.js

Fixes #158. At least theoretically it does - I couldn't make that case actually happen.

[fbjs-scripts] Handle case where requested package doesn't exist

---

package.json
packages/eslint-config-fbjs/CHANGELOG.md
packages/eslint-config-fbjs/index.js
packages/eslint-config-fbjs/package.json

Haven't made the switch internally yet, but this is supposed to be a drop-in replacement.

[eslint-config-fbjs] Use flowtype plugin

---

packages/babel-preset-fbjs/CHANGELOG.md
packages/babel-preset-fbjs/plugins/__tests__/rewrite-modules-test.js
packages/babel-preset-fbjs/plugins/rewrite-modules.js

[babel-preset-fbjs] rewrite typeof imports

---

packages/fbjs-scripts/third-party-module-map.json
packages/fbjs/package.json
packages/fbjs/src/unicode/UnicodeUtilsExtra.js

Use an object instead of a Immutable.Map, and remove Immutable. See D4141148.

Remove UnicodeUtilsExtra's dependence on Immutable

---

packages/signedsource/LICENSE
packages/signedsource/PATENTS
packages/signedsource/index.js
packages/signedsource/package.json

Moves this module out of React Native for easier reuse.

[signedsource] add signedsource

---

packages/fbjs-scripts/third-party-module-map.json
packages/fbjs/package.json
packages/fbjs/src/__forks__/setImmediate.js

add setImmediate

---

packages/fbjs/src/core/dom/getActiveElement.js

[fbjs] Fix undefined global in getActiveElement

---

packages/fbjs/src/core/isEmail.js
packages/fbjs/src/misc/getByPath.js
packages/fbjs/src/misc/isInternationalPhoneNumber.js

A couple modules from outside `shared` are in here so I made a new `misc` folder to hold anything that might be currently from other places in the repo.

[fbjs] Add a few more modules

---

packages/eslint-config-fbjs/package.json

**Summary**
Trying to get ESLint v4 in yarnpkg/yarn#3962. Related: facebook/jest#4072
**Test plan**
CI.

Upgrade: Upgrade ESLint peerDep to support v4

---

package.json
packages/eslint-config-fbjs/README.md
packages/eslint-config-fbjs/index.js
packages/eslint-config-fbjs/package.json

This doesn't include the prettier config / integration. We'll want to
figure that out but it's a bit tricky so punting.
Followup to #254

[eslint-config-fbjs] Sync from internal, update packages

---

CODE_OF_CONDUCT.md

Even though we don't really expect community contributions to `fbjs`, we still should add a `CODE_OF_CONDUCT.md`.
**why make this change?:**
Facebook Open Source provides a Code of Conduct statement for all
projects to follow, to promote a welcoming and safe open source community.
Exposing the COC via a separate markdown file is a standard being
promoted by Github via the Community Profile in order to meet their Open
Source Guide's recommended community standards.
As you can see, adding this file will improve [the fbjs community profile](https://github.com/facebook/fbjs/community)
checklist and increase the visibility of our COC.
**test plan:**
Viewing it on my branch -
**issue:**
internal task t23481323

Adding `CODE_OF_CONDUCT.md`

---

packages/eslint-config-fbjs/package.json

Set ~0.0.8 as minimum for peer dep of eslint-plugin-relay

---

packages/babel-preset-fbjs/package.json
packages/babel-preset-fbjs/yarn.lock
packages/fbjs/package.json
packages/fbjs/src/core/__tests__/debounceCore-test.js
packages/fbjs/src/core/__tests__/memoizeStringOnly-test.js
packages/fbjs/yarn.lock

Was looking at using yarn workspaces which in the end I didn't finish, but the jest upgrade still seems worthwhile to keep the dependency updated.

[babel-preset-fbjs][fbjs] Jest upgrade

---

packages/babel-preset-fbjs/package.json

Some peer dependencies are missing. This diff fixes that.

Fixes dependencies

---

packages/fbjs/src/performance/__tests__/performanceNow-test.js
packages/fbjs/src/performance/performanceNow.js

Fixes https://github.com/facebook/react-native/issues/16151 in `react-native`

fix/polyfill performance.now for react-native

---

packages/babel-preset-fbjs/plugins/inline-requires.js

In order to be able to inline requires in code that still contains `import`/`export`, types, etc; we need to avoid it crashing when an unsupported inlinement happens. We also make sure to not fully remove the `require` if it happens, which means that code will still work if the `require` is really needed.

Safe fallback if an inlinement cannot happen

---

packages/fbjs-scripts/CHANGELOG.md
packages/fbjs-scripts/package.json

Bump fbjs-scripts to 1.1.0

---

packages/fbjs/gulpfile.js
packages/fbjs/package.json
packages/fbjs/yarn.lock

This fixes incompatabilities between node < 12 and gulp 3. I did the
bare minimum to make the build work.

Upgrade to gulp 4.0

---

packages/fbjs-scripts/package.json
packages/fbjs-scripts/yarn.lock
packages/fbjs/package.json
packages/fbjs/src/key-mirror/keyMirrorRecursive.js
packages/fbjs/yarn.lock

Flow v0.167 bans "@flow weak". Let's upgrade this module

Fix @flow weak usage

---

.github/workflows/ci.yml

- Update list of current & lts releases to test with
- Update to setup-node@v2 (with built in caching between versions in the
matrix)

Update CI Action

---

packages/eslint-config-fbjs/CHANGELOG.md
packages/eslint-config-fbjs/package.json

[eslint-config-fbjs] v4.0.0

---

packages/eslint-config-fbjs-opensource/CHANGELOG.md
packages/eslint-config-fbjs-opensource/package.json

[eslint-config-fbjs-opensource] v3.0.0

---

packages/eslint-config-fb-strict/package.json

[eslint-config-fbjs-strict] v27.0.0
